" iMprove yo'self -- please do not remove
set nocompatible

" white text gets boring after awhile
syntax enable

" configure Vundle
filetype on " without this vim emits a zero exit status, later, because of :ft off
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/dotfiles/vim/Vundle.vim
call vundle#rc()

" install Vundle bundles
if filereadable(expand("~/dotfiles/vim/vimrc.bundles"))
	source ~/dotfiles/vim/vimrc.bundles
endif

source ~/dotfiles/vim/plugins/whitespace.vim

" ensure ftdetect et al work by including this after the Vundle stuff
filetype plugin indent on

set autoindent
set autoread                                                 " reload files when changed on disk, i.e. via `git checkout`
set backspace=2                                              " Fix broken backspace in some setups
set backupcopy=yes                                           " see :help crontab
set clipboard=unnamed                                        " yank and paste with the system clipboard
set directory-=.                                             " don't store swapfiles in the current directory
set encoding=utf-8
set expandtab                                                " expand tabs to spaces
set ignorecase                                               " case-insensitive search
set incsearch                                                " search as you type
set laststatus=2                                             " always show statusline
set list                                                     " show trailing whitespace
set listchars=tab:▸\ ,trail:▫
set number                                                   " show line numbers
set ruler                                                    " show where you are
set scrolloff=3                                              " show context above/below cursorline
set shiftwidth=2                                             " normal mode indentation commands use 2 spaces
set showcmd
set smartcase                                                " case-sensitive search if any caps
set softtabstop=2                                            " insert mode tab and backspace use 2 spaces
set tabstop=8                                                " actual tabs occupy 8 characters
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc
set wildmenu                                                 " show a navigable menu for tab completion
set wildmode=longest,list,full

autocmd BufRead,BufNewFile *.c,*.h,*.cpp set noic cin noexpandtab


" keyboard shortcuts
let mapleader = ','
" Remaps to make navigating splits easier
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Plugin-related shortcuts
nnoremap <leader>d :NERDTreeToggle<CR>
nnoremap <leader>f :NERDTreeFind<CR>
nnoremap <leader>t :CtrlP<CR>
nnoremap <leader>T :CtrlPClearCache<CR>:CtrlP<CR>
nnoremap <leader><space> :call whitespace#strip_trailing()<CR>

" Making it easier to apply Macros
nnoremap Q @q
vnoremap Q :norm @q<cr>

" -------- BUFFERS --------
" To open a new empty buffer
" This replaces :tabnew which I used to bind to this mapping
nmap <leader>T :enew<cr>

" Move to the next buffer
nmap <leader>l :bnext<CR>

" Move to the previous buffer
nmap <leader>h :bprevious<CR>

" This fixes an annoying airline thing
let g:bufferline_echo = 0

" plugin-specific settings
let g:ctrlp_match_window = 'order:ttb,max:20'
let g:NERDSpaceDelims=1


" NERDTree Specific configuration
" Ignoring pyc files
let NERDTreeIgnore = ['\.pyc$']


" Terminal and other visual-related settings
" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

let base16colorspace=256  " Access colors present in 256 colorspace

" Theme for bottom bar
let g:airline_theme='base16'

" Language-specific configuration

" Python Syntax and other configuration
let g:python_highlight_all = 1
" nmap <leader>; :PymodeLintAuto<CR>

set fillchars+=stl:\ ,stlnc:\

set undofile
set undodir=~/.vim/undodir
