export PLATFORM=`uname -s`
mkdir -p ~/.zsh/cache

# Source all of our zsh files
export ZSH=~/dotfiles/zsh
typeset -U config_files
config_files=($ZSH/*.zsh)

# load the path files
for file in ${(M)config_files:#*/path.zsh}
do
  source $file
done

# load everything but the path file
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}
do
  source $file
done

# languages
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_CTYPE=C

# completion
autoload -U compinit; compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # match uppercase from lowercase

# viewing / editing
export PAGER='less'
export EDITOR='vim'
export MUTT_EDITOR='vim'

autoload colors; colors # ANSI color codes

# history
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_DUPS
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=$HOME/.zsh/history
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search


# user-dependent settings
if [[ "`id -u`" -eq 0 ]]; then
  umask 022
else
  umask 077
fi

# Bringing in Logjammin'
. ~/logjammin/todo.sh

# Other
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export BOTO_CONFIG="$HOME/.aws/config"

# Grep Colors
export GREP_COLORS='0;30;42'

# Autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

unset config_files
